name: .NET Setup
author: Florian Bernd
description: Sets up the requested .NET versions.

inputs:
  shell:
    description: The default shell to use for this composite action.
    type: string
    required: false
    default: bash
  dotnet-version:
    description: The .NET SDK versions to set up. Supports multi-line strings.
    type: string
    required: false
    default: 6.0.x
  disable-problem-matcher:
    description: Removes the default .NET problem matcher.
    type: boolean
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Configure Environment
      shell: ${{ inputs.shell }}
      run: |
        echo "DOTNET_NOLOGO=1" >> $GITHUB_ENV
        echo "DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1" >> $GITHUB_ENV
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
        echo "DOTNET_GENERATE_ASPNET_CERTIFICATE=1" >> $GITHUB_ENV

    - name: Disable Problem Matcher
      if: inputs.problem-error-matcher
      shell: ${{ inputs.shell }}
      run: |
        echo "::remove-matcher owner=csc::"
